version: 0.1
env:
   parameter-store:
      access_key_id: /codebuild/access_key_id
      secret_access_key: /codebuild/secret_access_key
phases:
   install:
       commands:
           - echo Installing source NPM dependencies...
           - npm install
           - npm install -g @angular/cli
   build:
       commands:
           - echo Build started on `date`
           - ng build --prod
   post_build:
        commands:
           - aws s3 sync --delete dist/project2 s3://project2images
artifacts:
   files:
       - '**/*'
   base-directory: 'project2*'
   discard-paths: yes
